<?php require_once Env::dir() . "/view/template/header.phtml" ?>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Create a Post</h1>

            <form action="<?= $_SERVER['PHP_SELF'] ?>" method="POST">

                <div class="form-group">
                    <label for="title">Title <span class="require">*</span></label>
                    <input type="text" class="form-control" name="title" />
                </div>

                <div class="form-group">
                    <label for="description">Content</label>
                    <textarea rows="5" class="form-control" name="content" ></textarea>
                </div>

                <div class="form-group">
                    <p><span class="require">*</span> - required fields</p>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Create" name="post">
                </div>

                <div class="form-group">
                    <p class="text-danger"><?= $error ?? '' ?></p>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require_once Env::dir() . "/view/template/footer.phtml" ?>

