<?php require_once Env::dir() . "/view/template/header.phtml"; ?>
<main>
    <div class="row-cols-6">
        <div class="col-sm-12">
            <h1 class="indextitle">The forum</h1>
        </div>
    </div>

    <div class="row-cols-6">
        <div class="col-sm-12">
           <div class="icon">
               <img src="../css/images/icon.jpg">
           </div>
            <h4 class="indextitle">Welcome to the Forum!</h4>
            <p class="indextitle"> Hi and welcome to the forum where you can discuss everything about anything!! <br>
                once you have created an account head over to the posts section to see what everyone is talking about.  </p>
        </div>
    </div>
</main>

<?php require_once Env::dir() . "/view/template/footer.phtml"; ?>

