<?php require_once Env::dir() . "/view/template/header.phtml" ?>

<div class="indextitle"><h3>Posts you're following:</h3></div>

<div class="wrapper-main">
    <section class="section-default mb-12">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <ul class="list-group">
                        <?php if (Account::isLoggedIn()) : ?>
                            <?php foreach (Account::user()->watchlist() as $watchlistItem) : ?>
                                <li class="list-group-item">
                                    <a href="../viewpost.php?id=<?= $watchlistItem->post->id ?>">
                                        <?= $watchlistItem->post->title?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</div>

<div class="col-md-12">
    <div class="d-flex flex-row justify-content-between align-items-center mb-4">
        <h1 class="post-style">Recent Posts</h1>
        <a href="create.php" class="text-right btn btn-primary">Create a post!</a>
    </div>
    <div id="posts"></div>
</div>

<script>
    let posts = [];
    let postContainer = document.getElementById('posts');
    let skip = 0;
    let loading = false;

    window.onscroll = function(ev) {
        if ((window.innerHeight + window.pageYOffset) >= document.body.offsetHeight - 100) {
            getposts();
        }
    };

    getposts();

    function getposts() {   // gets post data
        if (loading)
            return;
        console.log("get posts - " + skip);
        loading = true;
        fetch(`data/posts.php?offset=${skip}`)
            .then(res => res.json())
            .then(data => {
                for (let post of data) {
                    postContainer.innerHTML +=
                        `<div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">${post.title}</h5>
                            <p class="card-text">${post.content.substr(0, 15) + '...'}</p>
                            <p class="card-text"><small class="text-muted">${post.date}</small></p>
                            <a href="viewpost.php?id=${post.id}" class="btn btn-info btn-small">Read More</a>
                        </div>
                    </div>`;
                }
                loading = false;
                skip += 5;
            }).catch(err => console.error(err));
    }
</script>

<?php require_once Env::dir() . "/view/template/footer.phtml" ?>
