<?php require_once Env::dir() . "/view/template/header.phtml" ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="indextitle">Search for a Post</h2>
            <form action="<?= $_SERVER['PHP_SELF'] ?>" method="POST">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" value="<?= $_POST['search'] ?? '' ?>" required placeholder="Enter search term...">
                </div>
                <input type="submit" class=" btn btn-primary" name="submit" value="Search">
            </form>
            <?php if (isset($posts) && !empty($posts)) : ?>
                <?php
                /**
                 * @var $post Post
                 */
                foreach ($posts as $post) : ?>
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title"><?= $post->title ?></h5>
                            <p class="card-text"><?= substr($post->title, 0, 15) . "..."?></p>
                            <p class="card-text"><small class="text-muted"><?= $post->stringDate() ?></small></p>
                            <a href="viewpost.php?id=<?= $post->id ?>" class="btn btn-info btn-small">Read More</a>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php require_once Env::dir() . "/view/template/footer.phtml" ?>
