<footer class="page-footer font-small stylish-color-dark pt-4">
    <div class="container text-center text-md-left">
        <div class="row">
            <div class="col-md-4 mx-auto">
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">The forum</h5>
            </div>
            <hr class="clearfix w-100 d-md-none">
            <div class="col-md-4 mx-auto">
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Contact Us</h5>
                <ul class="list-unstyled">
                    <li>
                        <p>TheForum@TheForum.com</p>
                    </li>
                    <li>
                        <p> 01253 123 321</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <ul class="list-unstyled list-inline text-center py-2">
        <li class="list-inline-item">
            <h5 class="mb-1">Register for free</h5>
        </li>
        <li class="list-inline-item">
            <a href="signup.php" class="btn btn-danger btn-rounded">Sign up!</a>
        </li>
    </ul>

</footer>

